### ISSUE TITLE
Invalid API endpoint for NA region

### ISSUE THREAD

**Issue by reven86** [svartalf/python-wargaming#12]
Choosing NA region leads to calls to https://api.worldoftanks.na instead of https://api.worldoftanks.com

```
wot = wargaming.WoT('demo', region='na', language='ru')
redirect_to = wot.auth.login(nofollow=1, redirect_uri='...')['location']
```

```
ConnectionError: DNS lookup failed for URL: https://api.worldoftanks.na/wot/auth/login/?redirect_uri=
```

EDIT: A quick fix would be to patch region_url function and make a special case for NA region. I can open a pull request if it's an appropriate solution.

**Comment by monester** [comment]
Hi, yeah. Such substitution works for all regions except na. Fixed and published update on pypi.
