### ISSUE TITLE
More of a heads up

### ISSUE THREAD

**Issue by Rob-bb** [svartalf/python-wargaming#2]
Strongholds API has been released.

**Comment by svartalf** [comment]
Thanks for a note!
Added in 309fe583374ba810c91a2de9b5920d0743bebbe6.
I had uploaded new package version onto a PyPI, so you can check it for a new features.

**Comment by Rob-bb** [comment]
Hi, seems to have lost a few features which I see were deprecated.  
My fault for not paying attention so now I have to go fix a few things.  

Thanks for making this, we appreciate it.   :)

**Comment by svartalf** [comment]
@rob-bb, yeah, I was thinking about a some deprecation policy, but current implementation was not good enough. Maybe a little later :)

Thanks for a feedback

**Comment by Rob-bb** [comment]
It's all good, it's not your job to do my homework. ;)
