### ISSUE TITLE
Uptodateness

### ISSUE THREAD

**Issue by Rob-bb** [svartalf/python-wargaming#4]
Hi, no issue as such, I was just wondering how current this is or how up to date it is with the current war gaming api?

**Comment by svartalf** [comment]
I have no time to maintain it right now, sorry.
As I remember. latest commits were targeted to the July 2015 Wargaming API updates.

Also, you can create an PR and I'll update a PyPI package.

**Comment by monester** [comment]
Updated to latest 2016.6 version of api
